from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any


MetricRow = dict[str, Any]


def load_metrics(path: Path) -> list[MetricRow]:
    rows: list[MetricRow] = []
    with path.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as error:
                raise ValueError(f"invalid JSON at line {line_number}") from error

    if not rows:
        raise ValueError(f"metrics file is empty: {path}")
    return rows


def group_by_split(rows: list[MetricRow]) -> dict[str, list[MetricRow]]:
    grouped: dict[str, list[MetricRow]] = defaultdict(list)
    for row in rows:
        grouped[str(row.get("split", "unknown"))].append(row)
    return grouped


def points(rows: list[MetricRow], metric_name: str) -> tuple[list[float], list[float]]:
    x_values: list[float] = []
    y_values: list[float] = []

    for row in rows:
        if metric_name not in row:
            continue
        x = row.get("global_step", row.get("epoch"))
        if x is None:
            continue
        x_values.append(float(x))
        y_values.append(float(row[metric_name]))

    return x_values, y_values


def plot_metrics(rows: list[MetricRow], output_path: Path) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as error:
        raise RuntimeError(
            "matplotlib is required for plotting. Install it with: "
            'python3 -m pip install -e ".[viz]"'
        ) from error

    grouped = group_by_split(rows)
    fig, axes = plt.subplots(3, 1, figsize=(11, 10), sharex=True)

    for split, split_rows in grouped.items():
        if split == "train_epoch":
            continue

        loss_x, loss_y = points(split_rows, "loss")
        if loss_y:
            axes[0].plot(loss_x, loss_y, marker="o", linewidth=1.5, label=split)

        ppl_x, ppl_y = points(split_rows, "perplexity")
        if ppl_y:
            axes[1].plot(ppl_x, ppl_y, marker="o", linewidth=1.5, label=split)

    train_epoch_rows = grouped.get("train_epoch", [])
    epoch_x, epoch_loss = points(train_epoch_rows, "loss")
    if epoch_loss:
        axes[0].plot(
            epoch_x,
            epoch_loss,
            marker="s",
            linestyle="--",
            linewidth=1.5,
            label="train_epoch",
        )

    lr_x: list[float] = []
    lr_y: list[float] = []
    for split_rows in grouped.values():
        x_values, y_values = points(split_rows, "learning_rate")
        lr_x.extend(x_values)
        lr_y.extend(y_values)
    if lr_y:
        axes[2].plot(lr_x, lr_y, color="#2563eb", linewidth=1.5)

    axes[0].set_title("Training and validation loss")
    axes[0].set_ylabel("loss")
    axes[0].grid(alpha=0.25)
    axes[0].legend()

    axes[1].set_title("Perplexity")
    axes[1].set_ylabel("perplexity")
    axes[1].grid(alpha=0.25)
    axes[1].legend()

    axes[2].set_title("Learning rate")
    axes[2].set_xlabel("global step")
    axes[2].set_ylabel("lr")
    axes[2].grid(alpha=0.25)

    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=160)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot summarizer training metrics")
    parser.add_argument(
        "--metrics-path",
        default="runs/baseline/metrics.jsonl",
        help="Path to metrics JSONL generated by scripts/train.py",
    )
    parser.add_argument(
        "--output-path",
        default="runs/baseline/training_curves.png",
        help="Where to save the plot image",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = load_metrics(Path(args.metrics_path))
    plot_metrics(rows, Path(args.output_path))
    print(f"saved plot to {args.output_path}")


if __name__ == "__main__":
    main()

